---
title: "Figure 1"
author: "Nick Pokorzynski"
date: "4/14/2020"
output:
  word_document: default
  pdf_document: default
---
```{r}
#Fig 1b
setwd("~/Documents/Carabeo Lab/R Code/Paper 2/Figure 1")
library(ggplot2)
library(ggpubr)
gdna<-read.csv("Fig1b.csv")
gdna$Treatment2<-factor(gdna$Treatment, levels=c("Mock", "Bpd", "Trp"))
gdna$ID2<-factor(gdna$ID, levels=c("24 hpi", "18+6 Bpd", "18+6 Trp-", "24 Bpd", "24 Trp-"))
gdnaaov<-aov(Value~ID, data=gdna)
summary(gdnaaov)
TukeyHSD(x=gdnaaov)
ggbarplot(gdna, x="ID2", y="Log10_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3")) + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log10 Genome Equivalents/ng gDNA") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=gdna, x="ID2", y="Log10_Value", colour="black") + geom_signif(comparisons=list(c("18+6 Bpd", "18+6 Trp-"), c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 Bpd", "24 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-")), annotation=c("ns", "***", "**", "ns", "***", "***"), y_position=c(5, 5.5, 6, 4, 6.5, 7)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1))
```

```{r}
#Fig 1c
setwd("~/Documents/Carabeo Lab/R Code/Paper 2/Figure 1")
library(ggplot2)
library(ggpubr)
rt<-read.csv("Fig1c.csv")
rt$Treatment2<-factor(rt$Treatment, levels=c("Mock", "Bpd", "Trp"))
rt$ID2<-factor(rt$ID, levels=c("24 hpi", "18+6 Bpd", "18+6 Trp-", "24 Bpd", "24 Trp-"))
omcB<-subset(rt, Gene%in%c("omcB"))
omcBaov<-aov(Log2_Value~ID, data=omcB)
summary(omcBaov)
TukeyHSD(x=omcBaov)
ggbarplot(omcB, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3"), title="omcB") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=omcB, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-")), annotation=c("ns", "ns", "***", "***"), y_position=c(10, 11, 12, 13)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
euo<-subset(rt, Gene%in%c("euo"))
euoaov<-aov(Log2_Value~ID, data=euo)
summary(euoaov)
TukeyHSD(x=euoaov)
ggbarplot(euo, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3"), title="euo") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=euo, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-")), annotation=c("ns", "ns", "***", "*"), y_position=c(10, 11, 12, 13)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
```


```{r}
#Fig 1d
setwd("~/Documents/Carabeo Lab/R Code/Paper 2/Figure 1")
library(ggplot2)
library(ggpubr)
rt<-read.csv("Fig1d.csv")
rt$Treatment2<-factor(rt$Treatment, levels=c("Mock", "Bpd", "Trp"))
rt$ID2<-factor(rt$ID, levels=c("24 hpi", "18+6 Bpd", "18+6 Trp-", "24 Bpd", "24 Trp-"))
trpR<-subset(rt, Gene%in%c("trpR"))
trpRaov<-aov(Log2_Value~ID, data=trpR)
summary(trpRaov)
TukeyHSD(x=trpRaov)
ggbarplot(trpR, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3"), title="trpR") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=trpR, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-"), c("18+6 Bpd", "18+6 Trp-"), c("24 Bpd", "24 Trp-")), annotation=c("ns", "***", "***", "***", "***", "***"), y_position=c(5, 11, 12, 13, 9.5, 10.5)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
trpB<-subset(rt, Gene%in%c("trpB"))
trpBaov<-aov(Log2_Value~ID, data=trpB)
summary(trpBaov)
TukeyHSD(x=trpBaov)
ggbarplot(trpB, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3"), title="trpB") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=trpB, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-"), c("18+6 Bpd", "18+6 Trp-"), c("24 Bpd", "24 Trp-")), annotation=c("**", "***", "***", "***", "***", "***"), y_position=c(5, 11, 12, 13, 9.5, 10.5)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
trpA<-subset(rt, Gene%in%c("trpA"))
trpAaov<-aov(Log2_Value~ID, data=trpA)
summary(trpAaov)
TukeyHSD(x=trpAaov)
ggbarplot(trpA, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("lightsteelblue4", "lightsteelblue1", "lightsteelblue3"), title="trpA") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=trpA, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "24 Bpd"), c("24 hpi", "24 Trp-"), c("18+6 Bpd", "18+6 Trp-"), c("24 Bpd", "24 Trp-")), annotation=c("***", "***", "***", "***", "***", "***"), y_position=c(5, 11, 12, 13, 9.5, 10.5)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
```

```{r}
#Fig 1e
setwd("~/Documents/Carabeo Lab/R Code/Paper 2/Figure 1")
library(ggplot2)
library(ggpubr)
rt<-read.csv("Fig1e.csv")
rt$ID2<-factor(rt$ID, levels=c("24 hpi", "18+6 Bpd", "18+6 Trp-", "18+6 Bpd + Trp-"))
rt$Treatment2<-factor(rt$Treatment, levels=c("Mock", "Bpd", "Trp", "Bpd + Trp"))
trpB<-subset(rt, Gene%in%c("trpB"))
trpBaov<-aov(Log2_Value~ID, data=trpB)
summary(trpBaov)
TukeyHSD(x=trpBaov)
ggbarplot(trpB, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("darkseagreen4", "darkseagreen", "darkseagreen3", "darkseagreen1"), title="trpB") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=trpB, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("18+6 Trp-", "18+6 Bpd + Trp-"), c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "18+6 Bpd + Trp-")), annotation=c("ns", "***", "***", "***"), y_position=c(10, 11, 12, 13)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
trpA<-subset(rt, Gene%in%c("trpA"))
trpAaov<-aov(Log2_Value~ID, data=trpA)
summary(trpAaov)
TukeyHSD(x=trpAaov)
ggbarplot(trpA, x="ID2", y="Log2_Value", add="mean_sd", fill="Treatment2", palette=c("darkseagreen4", "darkseagreen", "darkseagreen3", "darkseagreen1"), title="trpA") + scale_y_continuous(expand=expand_scale(mult=c(0,0.1))) + ylab(label="Log2 Transcript Expression") + rremove("legend") + theme(axis.text.x=element_text(angle=45, hjust=1)) + rremove("xlab") + geom_exec(geomfunc=geom_point, data=trpA, x="ID2", y="Log2_Value", colour="black") + geom_signif(comparisons=list(c("18+6 Trp-", "18+6 Bpd + Trp-"), c("24 hpi", "18+6 Bpd"), c("24 hpi", "18+6 Trp-"), c("24 hpi", "18+6 Bpd + Trp-")), annotation=c("ns", "**", "***", "***"), y_position=c(10, 11, 12, 13)) + theme(line=element_line(size=1, colour="black"), panel.border=element_rect(colour="black", fill="NA", size=1)) + theme(plot.title=element_text(hjust='0.5', face="italic"))
```
